"""Best-effort structural identification of the Top-15 features highlighted by STEP 4's
"Feature Importance" chart (Performance Charts group, "Plot Model" button).

Only descriptor families with a *reliable*, locally-verifiable definition are resolved:

- RDKit-native Morgan fingerprints generated by CODRUG itself (columns named "ECFP4_<i>",
  "FCFP6_<i>", "ECFP4_count_<i>" - see CODRUG._compute_rdkit_fp_single_mode): EXACT. The
  substructure is recovered by recomputing the very same fingerprint (same radius/useFeatures/
  fpSize/chirality) on a training-set molecule that actually has that bit set, then reading
  RDKit's bitInfoMap for it - the same technique used by the reference FCFP6 example this
  feature was requested from.
- "MACCSFP<n>" (PaDEL/CDK's 166 MACCS structural keys): BEST-EFFORT. PaDEL computes this
  descriptor via CDK, but RDKit ships the same public "166 keys" specification
  (MACCSkeys.smartsPatts) as its own descriptor - the closest verifiable local reference. A
  handful of keys are documented to differ subtly between toolkit implementations because the
  original textual spec is ambiguous for them - every resolved MACCS record is flagged as
  approximate via its "exact" field and "note".
- "PubchemFP<n>" (PaDEL/CDK's 881-bit PubChem CACTVS Substructure Fingerprint): EXACT, for the
  733 of 881 bits that describe a single fixed-topology substructure (NCBI's official spec
  Sections 3-7 - atom pairs, atom neighborhoods, and simple/complex SMARTS patterns). Resolved
  from a local reference table (BASE/DESCRIPTORS/pubchem_fingerprint_bits.json) built once from
  NCBI's official "PubChem Substructure Fingerprint V1.3" specification document - see
  build_pubchem_fingerprint_table() below. The remaining 148 bits (Sections 1-2: whole-molecule
  element/ring COUNT thresholds, e.g. ">= 2 aromatic rings") have no single substructure to draw
  by definition and are correctly left unresolved even though they're in the table.

Everything else - PaDEL's continuous 3D descriptors (e.g. MomentOfInertia), plain 1D/2D
physicochemical descriptors, etc. - has no reliable *local* substructure definition to draw from
without fabricating one, so it is left unresolved (functions return None) rather than guessing.
Callers should treat None as "not possible for this descriptor", not as an error.
"""

from __future__ import annotations

import io
import json
import os
import re
from functools import lru_cache
from typing import Any, Optional

try:
    from rdkit import Chem
    from rdkit.Chem import AllChem, Draw, MACCSkeys, rdFingerprintGenerator as rfg
    _RDKIT_AVAILABLE = True
except Exception:
    _RDKIT_AVAILABLE = False


# radius/useFeatures per family, matching CODRUG._compute_rdkit_fp_single_mode exactly.
_ECFP_FAMILIES = {
    "ECFP4": {"radius": 2, "use_features": False},
    "FCFP6": {"radius": 3, "use_features": True},
    "ECFP4_count": {"radius": 2, "use_features": False},
}

# Order matters: "ECFP4_count_" must be tried before the plainer "ECFP4_" pattern.
_COL_PATTERNS = [
    (re.compile(r"^ECFP4_count_(\d+)$"), "ECFP4_count"),
    (re.compile(r"^ECFP4_(\d+)$"), "ECFP4"),
    (re.compile(r"^FCFP6_(\d+)$"), "FCFP6"),
    (re.compile(r"^MACCSFP(\d+)$", re.IGNORECASE), "MACCSFP"),
    (re.compile(r"^PubchemFP(\d+)$", re.IGNORECASE), "PubchemFP"),
]

# BASE/DESCRIPTORS/pubchem_fingerprint_bits.json lives two directories up from this file
# (CODRUG/MODULES/module_feature_structures.py -> CODRUG/BASE/DESCRIPTORS/...).
_DEFAULT_PUBCHEM_TABLE_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "BASE", "DESCRIPTORS", "pubchem_fingerprint_bits.json",
)


def parse_descriptor_column(col_name: str) -> Optional[dict]:
    """Returns {'family': ..., 'index': int} for a column this module knows how to resolve, or
    None for anything else (e.g. PubchemFP*, MomentOfInertia, or any other descriptor name)."""
    name = str(col_name).strip()
    for pattern, family in _COL_PATTERNS:
        m = pattern.match(name)
        if m:
            return {"family": family, "index": int(m.group(1))}
    return None


def family_bit_indices(columns, family: str) -> list:
    """Every bit index for `family` found among `columns` - each pattern in _COL_PATTERNS is
    fully anchored (^...$), so e.g. family='ECFP4' never accidentally matches 'ECFP4_count_123'."""
    pattern = next((p for p, f in _COL_PATTERNS if f == family), None)
    if pattern is None:
        return []
    out = []
    for c in columns:
        m = pattern.match(str(c).strip())
        if m:
            out.append(int(m.group(1)))
    return out


def infer_fp_bits(columns, family: str) -> Optional[int]:
    """Best-effort recovery of the folded fingerprint size ('fpSize') originally used to
    generate `family`'s columns - needed by resolve_ecfp_bit to reproduce the same bit hashing.
    Feature selection performed after descriptor generation can remove columns (it never
    renumbers the survivors), so the true original size can't always be recovered exactly; this
    rounds the highest surviving bit index up to the next standard power-of-two fingerprint size
    (CODRUG's own 'Fingerprint bits' spinner only ever offers those)."""
    indices = family_bit_indices(columns, family)
    if not indices:
        return None
    max_idx = max(indices)
    for candidate in (128, 256, 512, 1024, 2048, 4096, 8192, 16384):
        if candidate > max_idx:
            return candidate
    return max_idx + 1


@lru_cache(maxsize=16)
def _get_morgan_gen(radius: int, n_bits: int, include_chirality: bool, use_features: bool):
    atom_inv_gen = rfg.GetMorganFeatureAtomInvGen() if use_features else rfg.GetMorganAtomInvGen()
    return rfg.GetMorganGenerator(
        radius=radius, includeChirality=include_chirality, useBondTypes=True,
        fpSize=n_bits, atomInvariantsGenerator=atom_inv_gen,
    )


def _env_to_smarts_smiles(mol, atom_idx: int, radius: int) -> tuple[Optional[str], Optional[str]]:
    """Extracts the atom environment of `radius` bonds around `atom_idx` in `mol` as a SMARTS
    string (always) and, when RDKit can round-trip it cleanly, a SMILES string too."""
    try:
        if radius == 0:
            atom = mol.GetAtomWithIdx(atom_idx)
            smarts = f"[#{atom.GetAtomicNum()}]"
            smiles = None
            try:
                single = Chem.MolFromSmarts(smarts)
                if single is not None:
                    smiles = Chem.MolToSmiles(single)
            except Exception:
                smiles = None
            return smarts, smiles
        env = Chem.FindAtomEnvironmentOfRadiusN(mol, radius, atom_idx)
        if not env:
            return None, None
        amap: dict = {}
        submol = Chem.PathToSubmol(mol, env, atomMap=amap)
        if submol is None or submol.GetNumAtoms() == 0:
            return None, None
        smarts = Chem.MolToSmarts(submol)
        try:
            smiles = Chem.MolToSmiles(submol)
        except Exception:
            smiles = None
        return smarts, smiles
    except Exception:
        return None, None


def resolve_ecfp_bit(family: str, bit_index: int, fp_bits: int, training_smiles, fp_chirality: bool = True,
                      max_search: int = 500) -> Optional[dict]:
    """Recomputes the same RDKit Morgan fingerprint CODRUG used to generate `family`'s columns
    on up to `max_search` training molecules, until one is found whose folded fingerprint
    actually has `bit_index` set, then recovers the responsible substructure via RDKit's
    bitInfoMap (same technique as the reference FCFP6 bit-interpretation example)."""
    if not _RDKIT_AVAILABLE or not training_smiles:
        return None
    spec = _ECFP_FAMILIES.get(family)
    if spec is None:
        return None
    gen = _get_morgan_gen(spec["radius"], fp_bits, bool(fp_chirality), spec["use_features"])

    checked = 0
    for smi in training_smiles:
        if checked >= max_search:
            break
        if smi is None:
            continue
        smi = str(smi).strip()
        if not smi or smi.lower() == "nan":
            continue
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            continue
        checked += 1
        info = rfg.AdditionalOutput()
        info.AllocateBitInfoMap()
        fp = gen.GetFingerprint(mol, additionalOutput=info)
        if bit_index >= fp.GetNumBits() or not fp.GetBit(bit_index):
            continue
        envs = info.GetBitInfoMap().get(bit_index)
        if not envs:
            continue
        atom_idx, radius = envs[0]
        smarts, smiles = _env_to_smarts_smiles(mol, atom_idx, radius)
        if smarts is None:
            continue
        return {
            "family": family, "bit_index": bit_index, "radius": radius,
            "smarts": smarts, "smiles": smiles or "",
            "source_smiles": smi,
            "note": (
                "Recovered from a training-set molecule with this bit set (RDKit bitInfoMap). "
                "Folded fingerprints can map more than one substructure to the same bit "
                "(collision) - this is one such match, not necessarily the only one."
            ),
            "exact": True,
        }
    return None


def resolve_maccs_bit(bit_index: int) -> Optional[dict]:
    """MACCS key `bit_index` (1-166) via RDKit's own public MACCSkeys.smartsPatts table - the
    same standard '166 keys' specification PaDEL implements via CDK, though a few keys are
    documented to differ subtly between toolkit implementations."""
    if not _RDKIT_AVAILABLE:
        return None
    patt = MACCSkeys.smartsPatts.get(bit_index)
    if not patt:
        return None
    smarts = patt[0]
    smiles = ""
    try:
        query = Chem.MolFromSmarts(smarts)
        if query is not None:
            smiles = Chem.MolToSmiles(query)
    except Exception:
        smiles = ""
    return {
        "family": "MACCSFP", "bit_index": bit_index, "radius": None,
        "smarts": smarts, "smiles": smiles,
        "source_smiles": "",
        "note": (
            "RDKit's standard 166 MACCS key definition (public reference). PaDEL computes this "
            "descriptor via CDK - bit order usually matches but is known to differ for a few "
            "keys due to ambiguities in the original specification; treat as approximate."
        ),
        "exact": False,
    }


@lru_cache(maxsize=1)
def _load_pubchem_table(path: str) -> dict:
    try:
        with open(path, "r", encoding="utf-8") as f:
            payload = json.load(f)
    except Exception:
        return {}
    return {int(b["bit"]): b for b in payload.get("bits", [])}


def resolve_pubchem_bit(bit_index: int, table_path: Optional[str] = None) -> Optional[dict]:
    """PubChem CACTVS Substructure Fingerprint bit `bit_index` (0-880), from the local reference
    table (see build_pubchem_fingerprint_table()) built once from NCBI's official "PubChem
    Substructure Fingerprint V1.3" specification. Returns None when the table file is missing,
    `bit_index` is out of range, or the bit is a whole-molecule element/ring COUNT rule with no
    single fixed-topology substructure to draw (the table marks those 'drawable': false)."""
    table = _load_pubchem_table(table_path or _DEFAULT_PUBCHEM_TABLE_PATH)
    entry = table.get(int(bit_index))
    if not entry or not entry.get("drawable") or not entry.get("smarts"):
        return None
    return {
        "family": "PubchemFP", "bit_index": bit_index, "radius": None,
        "smarts": entry["smarts"], "smiles": entry.get("smiles", ""),
        "source_smiles": "",
        "note": (
            f"NCBI PubChem Substructure Fingerprint V1.3, official bit definition (Section "
            f"{entry.get('section')}: {entry.get('description', '')})."
        ),
        "exact": True,
    }


def resolve_feature(col_name: str, training_smiles=None, fp_bits: Optional[int] = None,
                     fp_chirality: bool = True, max_search: int = 500,
                     pubchem_table_path: Optional[str] = None) -> Optional[dict]:
    """Dispatches to the right resolver for `col_name`, or returns None when this descriptor
    family has no reliable local structural definition (MomentOfInertia, any plain 1D/2D
    physicochemical descriptor, an out-of-table PubChem bit, etc.) - the correct, honest outcome
    for 'when possible'."""
    parsed = parse_descriptor_column(col_name)
    if parsed is None:
        return None
    family, bit_index = parsed["family"], parsed["index"]
    if family == "PubchemFP":
        return resolve_pubchem_bit(bit_index, table_path=pubchem_table_path)
    if family == "MACCSFP":
        return resolve_maccs_bit(bit_index)
    if not fp_bits:
        return None
    return resolve_ecfp_bit(family, bit_index, fp_bits, training_smiles, fp_chirality, max_search)


def draw_structures_grid(records: list, legends: Optional[list] = None,
                          mols_per_row: int = 5, sub_img_size=(220, 180)):
    """Returns (svg_text, png_bytes) for a grid of the resolved substructures in `records`
    (each a dict with 'smiles' and/or 'smarts', as returned by resolve_feature) - drawn from
    SMILES when RDKit could round-trip one, else from the SMARTS as a query molecule. Entries
    RDKit can't parse/draw are silently skipped. Returns (None, None) if nothing could be drawn."""
    if not _RDKIT_AVAILABLE or not records:
        return None, None
    mols, used_legends = [], []
    for i, rec in enumerate(records):
        mol = None
        if rec.get("smiles"):
            mol = Chem.MolFromSmiles(rec["smiles"])
        if mol is None and rec.get("smarts"):
            mol = Chem.MolFromSmarts(rec["smarts"])
        if mol is None:
            continue
        try:
            AllChem.Compute2DCoords(mol)
        except Exception:
            pass
        mols.append(mol)
        used_legends.append(legends[i] if legends and i < len(legends) else rec.get("descriptor", ""))
    if not mols:
        return None, None

    svg_raw = Draw.MolsToGridImage(mols, molsPerRow=mols_per_row, subImgSize=sub_img_size,
                                    legends=used_legends, useSVG=True)
    # Depending on the RDKit build/environment, useSVG=True returns either a plain string or a
    # rich-display wrapper (e.g. inside Jupyter) - normalize to plain text either way.
    svg_text = svg_raw if isinstance(svg_raw, str) else getattr(svg_raw, "data", None)

    png_bytes = None
    try:
        png_img = Draw.MolsToGridImage(mols, molsPerRow=mols_per_row, subImgSize=sub_img_size,
                                        legends=used_legends, useSVG=False)
        buf = io.BytesIO()
        png_img.save(buf, format="PNG")
        png_bytes = buf.getvalue()
    except Exception:
        png_bytes = None

    return svg_text, png_bytes


# ==========================================================================================
# One-off/reproducible builder for BASE/DESCRIPTORS/pubchem_fingerprint_bits.json - not called
# at runtime by resolve_feature()/resolve_pubchem_bit() (they just read the JSON file), only
# here so the table can be regenerated from the source PDF if NCBI ever revises the spec. Run
# as a script: `python -m MODULES.module_feature_structures <path-to-pdftotext--layout-output>`.
# ==========================================================================================

_PUBCHEM_SECTION_RE = re.compile(r"^Section\s+(\d+):\s*(.*)$")
_PUBCHEM_BIT_ROW_RE = re.compile(r"^\s*(\d{1,3})\s{2,}(\S.*?)\s*$")
_PUBCHEM_NOISE_RES = [
    re.compile(r"^PubChem Substructure Fingerprint"),
    re.compile(r"^V1\.3"),
    re.compile(r"^\s*Page \d+ of \d+"),
    re.compile(r"^Bit Position\s+Bit Substructure"),
    re.compile(r"^Decoding PubChem Fingerprints"),
    re.compile(r"^Document Version History"),
]
_PUBCHEM_ELEMENT_COUNT_RE = re.compile(r"^>=\s*(\d+)\s+([A-Za-z]+)$")
_PUBCHEM_ORGANIC_SUBSET = {"B", "C", "N", "O", "P", "S", "F", "Cl", "Br", "I"}


def _parse_pubchem_bit_rows(text_lines: list) -> list:
    """Parses NCBI's 'PubChem Substructure Fingerprint V1.3' spec (as plain text - run the
    source PDF through `pdftotext -layout` first) into a flat [{'bit', 'text', 'section'}, ...]
    list, one entry per bit position (0-880)."""
    rows, current_section = [], None
    i, n = 0, len(text_lines)
    while i < n:
        line = text_lines[i].rstrip("\n")
        stripped = line.strip()
        if not stripped or any(p.match(line) for p in _PUBCHEM_NOISE_RES):
            i += 1
            continue
        m = _PUBCHEM_SECTION_RE.match(stripped)
        if m:
            current_section = int(m.group(1))
            i += 1
            continue
        bm = _PUBCHEM_BIT_ROW_RE.match(line)
        if bm and current_section is not None:
            rows.append({"bit": int(bm.group(1)), "text": bm.group(2).strip(), "section": current_section})
        i += 1
    return rows


def _bracket_bare_elements(text: str, known_elements: set) -> str:
    """Wraps element symbols outside SMARTS's unbracketed 'organic subset' (e.g. 'Si', 'Se',
    'H', 'Li') in brackets, e.g. 'C(~Si)(~H)' -> 'C(~[Si])(~[H])' - needed because Sections 4/5
    of the spec write those bare, which RDKit's SMARTS parser rejects outside brackets. Already-
    bracketed atoms (e.g. '[As]') are left untouched."""
    two_letter = sorted([e for e in known_elements if len(e) == 2], key=len, reverse=True)
    one_letter = sorted(e for e in known_elements if len(e) == 1)
    element_re = re.compile(r"(?<![\[\w])(" + "|".join(two_letter + one_letter) + r")(?![a-z\w])")
    return element_re.sub(lambda m: m.group(1) if m.group(1) in _PUBCHEM_ORGANIC_SUBSET else f"[{m.group(1)}]", text)


def build_pubchem_fingerprint_table(pdftotext_layout_text: str) -> dict:
    """Builds the payload saved to BASE/DESCRIPTORS/pubchem_fingerprint_bits.json from the raw
    text of NCBI's 'PubChem Substructure Fingerprint V1.3' spec PDF (extract it first with
    `pdftotext -layout list_fingerprints.pdf out.txt`, then pass `open(out.txt).read()` here).
    Raises AssertionError if the parse doesn't yield exactly bits 0-880 (the spec's fixed size) -
    better to fail loudly than silently ship a corrupted/incomplete table."""
    if not _RDKIT_AVAILABLE:
        raise RuntimeError("RDKit is required to validate the parsed SMARTS patterns.")
    rows = _parse_pubchem_bit_rows(pdftotext_layout_text.splitlines())
    assert {r["bit"] for r in rows} == set(range(881)), "Expected exactly bits 0-880 from the spec"

    known_elements = set()
    for r in rows:
        if r["section"] == 1:
            m = _PUBCHEM_ELEMENT_COUNT_RE.match(r["text"])
            assert m, f"Unexpected Section 1 row: {r['text']!r}"
            known_elements.add(m.group(2))

    records = []
    for r in sorted(rows, key=lambda r: r["bit"]):
        bit, text, section = r["bit"], r["text"], r["section"]
        entry = {"bit": bit, "section": section}
        if section == 1:
            m = _PUBCHEM_ELEMENT_COUNT_RE.match(text)
            count, element = int(m.group(1)), m.group(2)
            entry.update(kind="element_count", drawable=True, smarts=f"[{element}]",
                         description=f">= {count} atom(s) of element {element} in the whole molecule",
                         element=element, min_count=count)
        elif section == 2:
            entry.update(kind="ring_property", drawable=False, smarts="", description=text)
        elif section == 3:
            el1, el2 = text.split("-")
            entry.update(kind="atom_pair", drawable=True, smarts=f"[{el1}]~[{el2}]",
                         description=f"bonded atom pair {el1}-{el2} (any bond order)")
        elif section == 4:
            entry.update(kind="atom_neighbors", drawable=True,
                         smarts=_bracket_bare_elements(text, known_elements), description=text)
        elif section == 5:
            entry.update(kind="detailed_neighbors", drawable=True,
                         smarts=_bracket_bare_elements(text, known_elements), description=text)
        elif section == 6:
            entry.update(kind="simple_smarts", drawable=True, smarts=text, description=text)
        elif section == 7:
            entry.update(kind="complex_smarts", drawable=True, smarts=text, description=text)
        else:
            raise AssertionError(f"Unknown section {section} for bit {bit}")

        entry["smiles"] = ""
        if entry["drawable"]:
            query = Chem.MolFromSmarts(entry["smarts"])
            assert query is not None, f"Bit {bit}: SMARTS failed to parse: {entry['smarts']!r}"
            try:
                entry["smiles"] = Chem.MolToSmiles(query) or ""
            except Exception:
                entry["smiles"] = ""
        records.append(entry)

    return {
        "$schema_note": (
            "PubChem CACTVS Substructure Fingerprint (881 bits) bit definitions, parsed from the "
            "official NCBI specification 'PubChem Substructure Fingerprint V1.3' "
            "(http://pubchem.ncbi.nlm.nih.gov). Sections 3-7 (bits 263-880) are drawable SMARTS "
            "patterns taken verbatim (or lightly re-bracketed for RDKit SMARTS syntax) from the "
            "spec. Section 1 (bits 0-114) are single-element atom counts ('>= N <element>' over "
            "the WHOLE molecule) - drawn as a single query atom; the count threshold itself has "
            "no fixed substructure to draw and is kept only in 'description'. Section 2 (bits "
            "115-262) are ring COUNT/property rules (e.g. '>= 2 aromatic rings') with no single "
            "fixed-topology substructure - not drawable (drawable=false, smarts/smiles left "
            "empty); 'description' still carries the exact rule."
        ),
        "source": "PubChem Substructure Fingerprint V1.3 (2009-05-01), http://pubchem.ncbi.nlm.nih.gov",
        "total_bits": len(records),
        "sections": {
            "1": "Hierarchic Element Counts",
            "2": "Rings in a canonic Extended Smallest Set of Smallest Rings (ESSSR) ring set",
            "3": "Simple atom pairs",
            "4": "Simple atom nearest neighbors",
            "5": "Detailed atom neighborhoods",
            "6": "Simple SMARTS patterns",
            "7": "Complex SMARTS patterns",
        },
        "bits": records,
    }


if __name__ == "__main__":
    import sys
    if len(sys.argv) != 2:
        print("Usage: python -m MODULES.module_feature_structures <pdftotext--layout-output.txt>")
        raise SystemExit(1)
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        _payload = build_pubchem_fingerprint_table(f.read())
    _out_path = _DEFAULT_PUBCHEM_TABLE_PATH
    os.makedirs(os.path.dirname(_out_path), exist_ok=True)
    with open(_out_path, "w", encoding="utf-8") as f:
        json.dump(_payload, f, indent=1, ensure_ascii=False)
    print(f"Wrote {_payload['total_bits']} bit definitions to {_out_path}")
